CREATE DATABASE CASO4;

USE CASO4;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNO_ID INT PRIMARY KEY,
ALUNO_NOME VARCHAR(100) NOT NULL,
ALUNO_DATANASC DATE NOT NULL,
ALUNO_RUA VARCHAR(50) NOT NULL,
ALUNO_NRUA INT,
ALUNO_BAIRRO VARCHAR(50) NOT NULL,
ALUNO_CIDADE VARCHAR(50) NOT NULL,
ALUNO_ESTADO VARCHAR(50) NOT NULL,
ALUNO_PAIS VARCHAR(50) NOT NULL,
ALUNO_CEP INT NOT NULL,
ALUNO_MODALIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
INSTRUTOR_ID INT PRIMARY KEY,
INSTRUTOR_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODALIDADES(
MODALIDADE_ID INT PRIMARY KEY,
MODALIDADE_NOME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PAGAMENTO(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS ENUM('PAGO', 'A PAGAR', 'ATRASADO') NOT NULL,
PAG_ALUNO_ID INT NOT NULL,
CONSTRAINT FK_ALUNO FOREIGN KEY (PAG_ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID)
);

CREATE TABLE IF NOT EXISTS MODALIDADES_INSTRUTORES(
MI_INSTRUTOR_ID INT NOT NULL,
MI_MODALIDADE_ID INT NOT NULL,
PRIMARY KEY (MI_INSTRUTOR_ID, MI_MODALIDADE_ID),
CONSTRAINT MI_PKFK_INSTRUTOR_ID FOREIGN KEY (MI_INSTRUTOR_ID) REFERENCES INSTRUTORES(INSTRUTOR_ID),
CONSTRAINT MI_PKFK_MODALIDADE_ID FOREIGN KEY (MI_MODALIDADE_ID) REFERENCES MODALIDADES(MODALIDADE_ID)
);

CREATE TABLE IF NOT EXISTS PLANO_TREINO(
PLANO_ID INT PRIMARY KEY,
PLANO_ALUNO_ID INT NOT NULL,
PLANO_INSTRUTOR_ID INT NOT NULL,
PLANO_MODALIDADE_ID INT NOT NULL,
CONSTRAINT FK_PLANO_ALUNO_ID FOREIGN KEY (PLANO_ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID),
CONSTRAINT FK_PLANO_INSTRUTOR_ID FOREIGN KEY (PLANO_INSTRUTOR_ID) REFERENCES MODALIDADES_INSTRUTORES(MI_INSTRUTOR_ID),
CONSTRAINT FK_PLANO_MODALIDADE_ID FOREIGN KEY (PLANO_MODALIDADE_ID) REFERENCES MODALIDADES_INSTRUTORES(MI_MODALIDADE_ID)
);

CREATE TABLE IF NOT EXISTS AULAS(
AULA_ID INT PRIMARY KEY,
AULA_HORA TIME NOT NULL,
AULA_CAPACIDADE INT NOT NULL,
AULA_INSTRUTOR_ID INT NOT NULL,
AULA_MODALIDADE_ID INT NOT NULL,
AULA_PLANO_TREINO_ID INT NOT NULL,
CONSTRAINT FK_AULA_INSTRUTOR_ID FOREIGN KEY (AULA_INSTRUTOR_ID) REFERENCES MODALIDADES_INSTRUTORES(MI_INSTRUTOR_ID),
CONSTRAINT FK_AULA_MODALIDADE_ID FOREIGN KEY (AULA_MODALIDADE_ID) REFERENCES MODALIDADES_INSTRUTORES(MI_MODALIDADE_ID),
CONSTRAINT FK_AULA_PLANO_TREINO_ID FOREIGN KEY (AULA_PLANO_TREINO_ID) REFERENCES PLANO_TREINO(PLANO_ID)
);

CREATE TABLE IF NOT EXISTS AULAS_ALUNOS(
AA_ALUNO_ID INT NOT NULL,
AA_AULA_ID INT NOT NULL,
PRIMARY KEY (AA_ALUNO_ID, AA_AULA_ID),
CONSTRAINT AA_PKFK_ALUNO_ID FOREIGN KEY (AA_ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID),
CONSTRAINT AA_PKFK_AULA_ID FOREIGN KEY (AA_AULA_ID) REFERENCES AULAS(AULA_ID)
);

ALTER TABLE ALUNOS ADD APAGAR VARCHAR(10);
ALTER TABLE ALUNOS MODIFY APAGAR INT;
ALTER TABLE ALUNOS CHANGE APAGAR APAGADO INT;
ALTER TABLE ALUNOS DROP COLUMN APAGADO;

ALTER TABLE INSTRUTORES ADD APAGAR VARCHAR(10);
ALTER TABLE INSTRUTORES MODIFY APAGAR INT;
ALTER TABLE INSTRUTORES CHANGE APAGAR APAGADO INT;
ALTER TABLE INSTRUTORES DROP COLUMN APAGADO;

ALTER TABLE MODALIDADES ADD APAGAR VARCHAR(10);
ALTER TABLE MODALIDADES MODIFY APAGAR INT;
ALTER TABLE MODALIDADES CHANGE APAGAR APAGADO INT;
ALTER TABLE MODALIDADES DROP COLUMN APAGADO;

ALTER TABLE PAGAMENTO ADD APAGAR VARCHAR(10);
ALTER TABLE PAGAMENTO MODIFY APAGAR INT;
ALTER TABLE PAGAMENTO CHANGE APAGAR APAGADO INT;
ALTER TABLE PAGAMENTO DROP COLUMN APAGADO;

ALTER TABLE MODALIDADES_INSTRUTORES ADD APAGAR VARCHAR(10);
ALTER TABLE MODALIDADES_INSTRUTORES MODIFY APAGAR INT;
ALTER TABLE MODALIDADES_INSTRUTORES CHANGE APAGAR APAGADO INT;
ALTER TABLE MODALIDADES_INSTRUTORES DROP COLUMN APAGADO;

ALTER TABLE PLANO_TREINO ADD APAGAR VARCHAR(10);
ALTER TABLE PLANO_TREINO MODIFY APAGAR INT;
ALTER TABLE PLANO_TREINO CHANGE APAGAR APAGADO INT;
ALTER TABLE PLANO_TREINO DROP COLUMN APAGADO;

ALTER TABLE AULAS ADD APAGAR VARCHAR(10);
ALTER TABLE AULAS MODIFY APAGAR INT;
ALTER TABLE AULAS CHANGE APAGAR APAGADO INT;
ALTER TABLE AULAS DROP COLUMN APAGADO;

ALTER TABLE AULAS_ALUNOS ADD APAGAR VARCHAR(10);
ALTER TABLE AULAS_ALUNOS MODIFY APAGAR INT;
ALTER TABLE AULAS_ALUNOS CHANGE APAGAR APAGADO INT;
ALTER TABLE AULAS_ALUNOS DROP COLUMN APAGADO;

CREATE TABLE APAGAR(
APAGA ENUM('FUI') PRIMARY KEY
);

DROP TABLE APAGAR;