CREATE DATABASE CASO5;

USE CASO5;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTE_CPF INT PRIMARY KEY,
CLIENTE_NOME VARCHAR(100) NOT NULL,
CLIENTE_DATANASC DATE NOT NULL,
CLIENTE_RUA VARCHAR(50) NOT NULL,
CLIENTE_NRUA INT,
CLIENTE_BAIRRO VARCHAR(50) NOT NULL,
CLIENTE_CIDADE VARCHAR(50) NOT NULL,
CLIENTE_CODPOSTAL VARCHAR(10) NOT NULL,
CLIENTE_PAIS VARCHAR(50) NOT NULL,
CLIENTE_STATUS TEXT NOT NULL 
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_ID INT PRIMARY KEY,
PROD_CATEGORIA VARCHAR(50) NOT NULL,
PROD_PRECO DECIMAL(10,2) NOT NULL,
PROD_QUANT INT
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_CNPJ INT PRIMARY KEY,
FORN_CONTATO TEXT NOT NULL,
FORN_NOME VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS(
VENDA_ID INT PRIMARY KEY,
VENDA_CLIENTE_ID INT NOT NULL,
CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (VENDA_CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENOS(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS ENUM('PAGO', 'A PAGAR', 'ATRASADO') NOT NULL,
PAG_FORMA ENUM('BOLETO', 'CARTAO DE CREDITO', 'PIX') NOT NULL,
PAG_VENDA_ID INT NOT NULL,
CONSTRAINT FK_VENDA_ID FOREIGN KEY (PAG_VENDA_ID) REFERENCES VENDAS(VENDA_ID)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FP_FORN_ID INT NOT NULL,
FP_PROD_ID INT NOT NULL,
PRIMARY KEY (FP_FORN_ID, FP_PROD_ID),
CONSTRAINT FP_PKFK_FORN_ID FOREIGN KEY (FP_FORN_ID) REFERENCES FORNECEDORES(FORN_CNPJ),
CONSTRAINT PF_PKFK_PROD_ID FOREIGN KEY (FP_PROD_ID) REFERENCES PRODUTOS(PROD_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
PV_PROD_ID INT NOT NULL,
PV_VENDA_ID INT NOT NULL,
CONSTRAINT PV_PKFK_PROD_ID FOREIGN KEY (PV_PROD_ID) REFERENCES PRODUTOS(PROD_ID),
CONSTRAINT PV_PKFK_VENDA_ID FOREIGN KEY (PV_VENDA_ID) REFERENCES VENDAS(VENDA_ID),
PV_QUANT INT NOT NULL,
PV_VALOR_VENDA DECIMAL(10,2) NOT NULL
);