CREATE DATABASE CASO1;

USE CASO1;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_COD INT PRIMARY KEY,
FORN_NOME VARCHAR(45) NOT NULL,
FORN_RUA VARCHAR(45) NOT NULL,
FORN_NUMRUA INT,
FORN_BAIRRO VARCHAR(45) NOT NULL,
FORN_ESTADO VARCHAR(45) NOT NULL,
FORN_PAIS VARCHAR(30) NOT NULL,
FORN_CODPOSTAL VARCHAR(10) NOT NULL,
FORN_TEL VARCHAR(15) NOT NULL,
FORN_CONTATO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESC TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAIS_COD INT PRIMARY KEY,
FILIAIS_NOME VARCHAR(30) NOT NULL,
FILIAIS_RUA VARCHAR(100) NOT NULL,
FILIAIS_NUMRUA INT,
FILIAIS_BAIRRO VARCHAR(50) NOT NULL,
FILIAIS_CIDADE VARCHAR(50) NOT NULL,
FILIAIS_ESTADO VARCHAR(50) NOT NULL,
FILIAIS_PAIS VARCHAR(50) NOT NULL,
FILIAIS_COSPOSTAL VARCHAR(10) NOT NULL,
FILIAIS_CAPACIDADE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
PEDIDOS_COD INT PRIMARY KEY,
PEDIDOS_DATA DATE NOT NULL,
PEDIDOS_HORA TIME NOT NULL,
PEDIDOS_PREV DATE NOT NULL,
PEDIDOS_STATUS VARCHAR(20) NOT NULL,
PEDIDOS_FORN INT NOT NULL,
CONSTRAINT FK_FORN FOREIGN KEY (PEDIDOS_FORN) REFERENCES FORNECEDORES(FORN_COD)
);

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3) NOT NULL,
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT NOT NULL,
CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PEDIDOS_COD)
);

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PEPR_PEDIDOS INT NOT NULL,
PEPR_PROD INT NOT NULL,
PRIMARY KEY (PEPR_PEDIDOS, PEPR_PROD),
CONSTRAINT PEPR_PKFK_PEDIDOS FOREIGN KEY (PEPR_PEDIDOS) REFERENCES PEDIDOS(PEDIDOS_COD),
CONSTRAINT PEPR_PKFK_PROD FOREIGN KEY (PEPR_PROD) REFERENCES PRODUTOS(PROD_COD),
PP_QUANT DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FIPR_FILIAIS INT NOT NULL,
FIPR_PROD INT NOT NULL,
PRIMARY KEY (FIPR_FILIAIS, FIPR_PROD),
CONSTRAINT FIPR_PKFK_PROD FOREIGN KEY (FIPR_PROD) REFERENCES PRODUTOS(PROD_COD),
CONSTRAINT FIPR_PKFK_FILIAIS FOREIGN KEY (FIPR_FILIAIS) REFERENCES FILIAIS(FILIAIS_COD)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FOPR_FORN INT NOT NULL,
FOPR_PROD INT NOT NULL,
PRIMARY KEY (FOPR_FORN, FOPR_PROD),
CONSTRAINT FOPR_PKFK_PROD FOREIGN KEY (FOPR_PROD) REFERENCES PRODUTOS(PROD_COD),
CONSTRAINT FOPR_PKFK_FORN FOREIGN KEY (FOPR_FORN) REFERENCES FORNECEDORES(FORN_COD)
);

ALTER TABLE FORNECEDORES ADD APAGAR VARCHAR(10);
ALTER TABLE FORNECEDORES MODIFY APAGAR INT;
ALTER TABLE FORNECEDORES CHANGE APAGAR APAGADO INT;
ALTER TABLE FORNECEDORES DROP COLUMN APAGADO;

ALTER TABLE PRODUTOS ADD APAGAR VARCHAR(10);
ALTER TABLE PRODUTOS MODIFY APAGAR INT;
ALTER TABLE PRODUTOS CHANGE APAGAR APAGADO INT;
ALTER TABLE PRODUTOS DROP COLUMN APAGADO;

ALTER TABLE FILIAIS ADD APAGAR VARCHAR(10);
ALTER TABLE FILIAIS MODIFY APAGAR INT;
ALTER TABLE FILIAIS CHANGE APAGAR APAGADO INT;
ALTER TABLE FILIAIS DROP COLUMN APAGADO;

ALTER TABLE PEDIDOS ADD APAGAR VARCHAR(10);
ALTER TABLE PEDIDOS MODIFY APAGAR INT;
ALTER TABLE PEDIDOS CHANGE APAGAR APAGADO INT;
ALTER TABLE PEDIDOS DROP COLUMN APAGADO;

ALTER TABLE RECEBIMENTOS ADD APAGAR VARCHAR(10);
ALTER TABLE RECEBIMENTOS MODIFY APAGAR INT;
ALTER TABLE RECEBIMENTOS CHANGE APAGAR APAGADO INT;
ALTER TABLE RECEBIMENTOS DROP COLUMN APAGADO;

ALTER TABLE PEDIDOS_PRODUTOS ADD APAGAR VARCHAR(10);
ALTER TABLE PEDIDOS_PRODUTOS MODIFY APAGAR INT;
ALTER TABLE PEDIDOS_PRODUTOS CHANGE APAGAR APAGADO INT;
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN APAGADO;

ALTER TABLE FILIAIS_PRODUTOS ADD APAGAR VARCHAR(10);
ALTER TABLE FILIAIS_PRODUTOS MODIFY APAGAR INT;
ALTER TABLE FILIAIS_PRODUTOS CHANGE APAGAR APAGADO INT;
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN APAGADO;

ALTER TABLE FORNECEDORES_PRODUTOS ADD APAGAR VARCHAR(10);
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY APAGAR INT;
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE APAGAR APAGADO INT;
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN APAGADO;

CREATE TABLE APAGAR(
APAGA ENUM('FUI') PRIMARY KEY
);

DROP TABLE APAGAR;