CREATE DATABASE CASO3;
 
 USE CASO3;
 
CREATE TABLE IF NOT EXISTS EMPRESAS(
CNPJ_EMPRESA INT PRIMARY KEY,
RAZAO_SOCIAL_EMPRESA VARCHAR(100) NOT NULL,
CONTATO_EMPRESA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
COD_EMPREGADO INT PRIMARY KEY,
NOME_EMPREGADO VARCHAR(100) NOT NULL,
CARGO_EMPREGADO VARCHAR(50) NOT NULL,
SALÁRIO_EMPREGADO DECIMAL(10,2) NOT NULL,
QUALIFICACAO_EMPREGADO VARCHAR(50) NOT NULL,
DATA_ADMISSAO_EMPREGADO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO(
COD_MANUT INT PRIMARY KEY,
DATA_MANUT DATE NOT NULL,
DESCRICAO_MANUT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTO(
COD_SUP INT PRIMARY KEY,
QUANT_SUP INT NOT NULL,
DATA_NECESSIDADE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTES(
COD_TIPO_COMP INT PRIMARY KEY,
FUNCAO_COMP TEXT NOT NULL
);

 CREATE TABLE IF NOT EXISTS CLIENTES(
 COD_CLIENTE INT PRIMARY KEY,
 RAZAO_SOCIAL_CLIENTE VARCHAR(100) NOT NULL,
 RAMO_ATIVIDADE VARCHAR(100) NOT NULL,
 DATA_CADASTRO DATE NOT NULL,
 CONTATO_CLIENTE VARCHAR(100),
 CNPJ_CLIENTE INT NOT NULL,
 COD_EMPRESA_CLIENTE INT NOT NULL,
 CONSTRAINT FK_EMPRESA_CLIENTE FOREIGN KEY (COD_EMPRESA_CLIENTE) REFERENCES EMPRESAS(CNPJ_EMPRESA)
 );
 
 CREATE TABLE IF NOT EXISTS FORNECEDORES(
 COD_FORN INT PRIMARY KEY,
 RAZAO_SOCIAL_FORN VARCHAR(100) NOT NULL,
 CONTATO_FORN TEXT NOT NULL,
 CNPJ_FORN INT NOT NULL,
 COD_EMPRESA_FORN INT NOT NULL,
 CONSTRAINT FK_EMPRESA_FORN FOREIGN KEY (COD_EMPRESA_FORN) REFERENCES EMPRESAS(CNPJ_EMPRESA)
 );
 
 CREATE TABLE IF NOT EXISTS TIPO_LOCAL(
 COD_TIPO INT PRIMARY KEY,
 TIPO_ESTABELECIMENTO VARCHAR(50) NOT NULL,
 COD_TIPO_FORN INT NOT NULL,
 COD_TIPO_CLIENTE INT NOT NULL,
 COD_TIPO_EMPREGADO INT NOT NULL,
 CONSTRAINT FK_TIPO_FORN FOREIGN KEY (COD_TIPO_FORN) REFERENCES FORNECEDORES(COD_FORN),
 CONSTRAINT FK_TIPO_CLIENTE FOREIGN KEY (COD_TIPO_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE),
 CONSTRAINT FK_TIPO_EMPREGADO FOREIGN KEY (COD_TIPO_EMPREGADO) REFERENCES EMPREGADOS(COD_EMPREGADO)
 );
 
 CREATE TABLE IF NOT EXISTS TELEFONES(
 COD_TEL INT PRIMARY KEY,
 TELEFONE INT NOT NULL,
 COD_TIPO_TEL INT NOT NULL,
 CONSTRAINT FK_TIPO_TELEFONE FOREIGN KEY (COD_TIPO_TEL) REFERENCES TIPO_LOCAL(COD_TIPO)
 );
 
 CREATE TABLE IF NOT EXISTS ENDERECOS(
 COD_ENDERECO INT PRIMARY KEY,
 BAIRRO VARCHAR(100) NOT NULL,
 RUA VARCHAR(100) NOT NULL,
 NUM_RUA INT,
 CIDADE VARCHAR(100) NOT NULL,
 ESTADO VARCHAR(100) NOT NULL,
 COMPLEMENTO VARCHAR(100) NOT NULL,
 CEP INT NOT NULL,
 COD_TIPO_ENDERECO INT NOT NULL,
 CONSTRAINT FK_TIPO_ENDERECO FOREIGN KEY (COD_TIPO_ENDERECO) REFERENCES TIPO_LOCAL(COD_TIPO)
 );
 
 CREATE TABLE IF NOT EXISTS ENCOMENDAS(
 COD_ENCOMENDA INT PRIMARY KEY,
 DATA_INCLUSAO_ENCOMENDA DATE NOT NULL,
 VALOR_TOTAL_ENCOMENDA DECIMAL(10,2) NOT NULL,
 VALOR_DESC_ENCOMENDA DECIMAL(10,2) NOT NULL,
 VALLOR_LIQ_ENCOMENDA DECIMAL(10,2) NOT NULL,
 FORMA_PAG VARCHAR(50) NOT NULL,
 QUANT_PARCELAS INT NOT NULL,
 COD_CLIENTE_ENCOMENDA INT NOT NULL,
 CONSTRAINT FK_CLIENTE_ENCOMENDA FOREIGN KEY (COD_CLIENTE_ENCOMENDA) REFERENCES CLIENTES(COD_CLIENTE)
 );
 
 CREATE TABLE IF NOT EXISTS COMPONENTES(
 COD_COMP INT PRIMARY KEY,
 NOME_COMP VARCHAR(50) NOT NULL,
 QUANT_COMP_ESTOQUE INT NOT NULL,
 PRECO_UNIT_COMP DECIMAL(10,2) NOT NULL,
 UNIDADE_COMP VARCHAR(50) NOT NULL,
 COD_SUP_COMP INT NOT NULL,
 COD_TIPO_COMP2 INT NOT NULL,
 CONSTRAINT FK_SUP_COMP FOREIGN KEY (COD_SUP_COMP) REFERENCES REGISTRO_SUPRIMENTO(COD_SUP),
 CONSTRAINT FK_TIPO_COMP2 FOREIGN KEY (COD_TIPO_COMP2) REFERENCES TIPO_COMPONENTES(COD_TIPO_COMP)
 );
 
 CREATE TABLE IF NOT EXISTS MAQUINAS(
 COD_MAQ INT PRIMARY KEY,
 TEMPO_VIDA_MAQ DATE NOT NULL,
 PRECO_UNIT_MAQ DECIMAL(10,2) NOT NULL,
 UNIDADE_MAQ VARCHAR(50) NOT NULL,
 COD_MANUT_MAQ INT NOT NULL,
 CONSTRAINT FK_MANUT_MAQ FOREIGN KEY (COD_MANUT_MAQ) REFERENCES REGISTRO_MANUTENCAO(COD_MANUT)
 );
 
 CREATE TABLE IF NOT EXISTS PRODUTOS(
 COD_PROD INT PRIMARY KEY,
 NOME_PROD VARCHAR(100) NOT NULL,
 COR_PROD VARCHAR(50) NOT NULL,
 DIMENSOES_PROD DECIMAL(5,2) NOT NULL,
 PESO_PROD DECIMAL(10,3) NOT NULL,
 PRECO_PROD DECIMAL(10,2) NOT NULL,
 TEMPO_FAB_PROD TIME NOT NULL,
 DESENHO_PROD BLOB NOT NULL, #BLOB É UM TIPO PARA ARMAZENAR CONTEÚDO BINÁRIO(IMAGENS)
 HOMAS_MAO_OBRA_PROD TIME NOT NULL,
 COD_COMP_PROD INT NOT NULL,
 COD_MAQ_PROD INT NOT NULL,
 CONSTRAINT FK_COMP_PROD FOREIGN KEY (COD_COMP_PROD) REFERENCES COMPONENTES(COD_COMP),
 CONSTRAINT FK_MAQ_PROD FOREIGN KEY (COD_MAQ_PROD) REFERENCES MAQUINAS(COD_MAQ)
 );
 
 CREATE TABLE IF NOT EXISTS REGISTRO_ESPECIFICO(
 RE_COD_COMP INT NOT NULL,
 RE_COD_MAQ INT NOT NULL,
 PRIMARY KEY (RE_COD_COMP, RE_COD_MAQ),
 RE_QAUNT_NECESSARIA INT NOT NULL,
 RE_UNIDADE VARCHAR(50) NOT NULL,
 RE_TEMPO_USO TIME NOT NULL,
 RE_HORAS_MAO_OBRA TIME NOT NULL,
 CONSTRAINT RE_PKFK_COD_MAQ FOREIGN KEY (RE_COD_MAQ) REFERENCES MAQUINAS(COD_MAQ),
 CONSTRAINT RE_PKFK_COD_COMP FOREIGN KEY (RE_COD_COMP) REFERENCES COMPONENTES(COD_COMP)
 );
 
 CREATE TABLE IF NOT EXISTS PRODUTO_ENCOMENDA(
 PE_COD_ENCOMENDA INT NOT NULL,
 PE_COD_PROD INT NOT NULL,
 PRIMARY KEY(PE_COD_ENCOMENDA, PE_COD_PROD),
 CONSTRAINT PE_PKFK_COD_ENCOMENDA FOREIGN KEY (PE_COD_ENCOMENDA) REFERENCES ENCOMENDAS(COD_ENCOMENDA),
 CONSTRAINT PE_PKFK_COD_PROD FOREIGN KEY (PE_COD_PROD) REFERENCES PRODUTOS(COD_PROD)
 );
 
 CREATE TABLE IF NOT EXISTS EMPREGADO_PRODUTO(
 EP_COD_EMPREGADO INT NOT NULL,
 EP_COD_PROD INT NOT NULL,
 PRIMARY KEY (EP_COD_EMPREGADO, EP_COD_PROD),
 CONSTRAINT EP_PKFK_COD_EMPREGADO FOREIGN KEY (EP_COD_EMPREGADO) REFERENCES EMPREGADOS(COD_EMPREGADO),
 CONSTRAINT EP_PKFK_COD_PROD FOREIGN KEY (EP_COD_PROD) REFERENCES PRODUTOS(COD_PROD)
 );
 
 CREATE TABLE IF NOT EXISTS FORNECEDOR_COMPONENTE(
 FC_COD_FORN INT NOT NULL,
 FC_COD_COMP INT NOT NULL,
 PRIMARY KEY (FC_COD_FORN, FC_COD_COMP),
CONSTRAINT FC_PKFK_COD_FRON FOREIGN KEY (FC_COD_FORN) REFERENCES FORNECEDORES(COD_FORN),
CONSTRAINT FC_PKFK_COD_COMP FOREIGN KEY (FC_COD_COMP) REFERENCES COMPONENTES(COD_COMP)
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUP_TIPO_COMP(
RSTC_COD_SUP INT NOT NULL,
RSTC_COD_TIPO_COMP INT NOT NULL,
PRIMARY KEY (RSTC_COD_SUP, RSTC_COD_TIPO_COMP),
CONSTRAINT RSTC_PKFK_COD_SUP FOREIGN KEY (RSTC_COD_SUP) REFERENCES REGISTRO_SUPRIMENTO(COD_SUP),
CONSTRAINT RSTC_PKFK_COD_TIPO_COMP FOREIGN KEY (RSTC_COD_TIPO_COMP) REFERENCES TIPO_COMPONENTES(COD_TIPO_COMP)
);